name: inzynierka
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: "2.5.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  google_fonts: ^2.1.0
  dartz: ^0.10.0
  connectivity: ^3.0.6
  dio: ^4.0.0
  get: ^4.3.8
  json_serializable: ^6.0.0
  flutter_svg: ^0.23.0+1
  image_picker: ^0.8.4+3
  camera: ^0.9.4+3
  tflite: ^1.1.2
  permission_handler: ^8.2.5
  rxdart: ^0.27.2
  flutter_bloc: ^7.3.1
  equatable: ^2.0.3
  freezed: ^0.15.0+1
  injectable: ^1.5.0
  get_it: ^7.2.0
  freezed_annotation: ^0.15.0
  image: ^3.0.8
  supercharged: ^2.1.1
  loading_indicator: ^3.0.2

  charts_flutter:
    git:
      url: https://github.com/google/charts
      path: charts_flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.4
  injectable_generator: null

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/tf/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Bold.ttf

